@echo off
setlocal

set "SCRIPT_DIR=%~dp0"
set "SDK_TARGET=%LOCALAPPDATA%\Android"
set "SDK_DRIVE=X:"
set "SDK_ROOT=%SDK_DRIVE%\Sdk"
set "LOCAL_PROPERTIES=%SCRIPT_DIR%local.properties"

subst %SDK_DRIVE% /d >nul 2>nul
subst %SDK_DRIVE% "%SDK_TARGET%"

if exist %SDK_ROOT% (
  >"%LOCAL_PROPERTIES%" (
    echo ## This file must *NOT* be checked into Version Control Systems,
    echo # as it contains information specific to your local configuration.
    echo # Generated by setup-android-sdk-drive.bat
    echo sdk.dir=X\:\\Sdk
  )
  echo [OK] %SDK_ROOT% is ready.
  echo [OK] local.properties was updated to sdk.dir=X\:\\Sdk
  exit /b 0
)

echo [FAIL] Could not map %SDK_DRIVE% to %SDK_TARGET%.
exit /b 1
